# Generated by Django 3.1.3 on 2020-11-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='problems',
            field=models.ManyToManyField(related_name='categories', to='finder.Problem'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='finder.problem'),
        ),
    ]
