# Generated by Django 3.0.8 on 2020-11-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20201105_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgesdaemon',
            name='codeforces_last_page',
        ),
        migrations.AddField(
            model_name='judgesdaemon',
            name='judge_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgesdaemon',
            name='last_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judgesdaemon',
            name='quantity',
            field=models.IntegerField(default=20),
        ),
    ]
