# Generated by Django 3.0.8 on 2020-12-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20201130_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgesdaemon',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
